### ISSUE TITLE
pynfl.schedule just returns a list of weeks

### ISSUE THREAD

**Issue by ghost** [jeremyjbowers/nfl-stats#3]
After running `pynfl` with `sudo`, I get only the following output:

```
Week 1
Week 2
Week 3
Week 4
Week 5
Week 6
Week 7
Week 8
Week 9
Week 10
Week 11
Week 12
Week 13
Week 14
Week 15
Week 16
Week 17
```

Is the script failing? If so, I would really appreciate a verbose flag to tell me what's going wrong (e.g. do I need an API key?). Thanks!

**Comment by jeremyjbowers** [comment]
There's demo code now that explains what's going on. Check out https://github.com/jeremyjbowers/nfl-stats/blob/master/pynfl/demo/__main__.py for more.
